FROM python:3.12-slim

WORKDIR /app

COPY live-app/requirements.txt requirements-app.txt
RUN pip install --no-cache-dir flask kafka-python-ng boto3 scikit-learn pandas joblib requests

COPY . .

EXPOSE 5000

CMD ["python", "dashboard/app.py"]
